version: "3"
services:
  postgres:
    container_name: postgres_django
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
        - .:/site
    ports:
      - "8000:80"

networks:
  postgres:
    driver: bridge